import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";

import Audio from "./audio/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon(1).ico" />
      </Head>

      {/*Homepage*/}

      <div className={styles.Homepage}>
        <div className={styles.wrapper}>
          <h1 className={styles.text}>Pokédex</h1>
          <Image
            className={styles.image}
            src="https://64.media.tumblr.com/326f907a6fd9bf251779cd0fdbb27bb7/tumblr_mrjd9jshOz1s4m43ho1_500.gif" //dominio immagine in next config
            alt="pokemon"
            width="1000"
            height="600"
          />
        </div>
      </div>
      <Audio />
      <footer className={styles.footer}>
        <p className={styles.text}>© 2024 fakePokédex </p>
      </footer>
    </>
  );
}
